on: [push]

jobs:
  custom-collector-action:
    runs-on: ubuntu-latest
    name: A job to build a custom OpenTelemetry Collector
    steps:
      - uses: actions/checkout@v3

      - uses: codeboten/collector-builder@main
        with:
          architecture: "arm64"
          os: "linux"
          container: "codeboten/test-collector"
