on: [push]

jobs:
  custom-collector-action:
    runs-on: ubuntu-latest
    name: A job to build a custom OpenTelemetry Collector
    steps:
      - uses: actions/checkout@main

      - name: Custom Collector Step
        uses: codeboten/collector-builder-action@v1
        with:
          architecture: "arm64"
          os: "darwin"

      - uses: actions/upload-artifact@v3
        with:
          name: otelcolaction
          path: _build/otelcolaction
